# Generated by Django 5.2.3 on 2025-06-16 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumni Connection',
                'verbose_name_plural': 'Alumni Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'receiver'], name='directory_a_request_ebcd28_idx'), models.Index(fields=['status'], name='directory_a_status_6f0ff7_idx')],
                'unique_together': {('requester', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveIntegerField()),
                ('major', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('current_job', models.CharField(blank=True, max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=100)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumni Profile',
                'verbose_name_plural': 'Alumni Profiles',
                'ordering': ['-graduation_year', 'user__first_name', 'user__last_name'],
                'indexes': [models.Index(fields=['graduation_year'], name='directory_a_graduat_edde89_idx'), models.Index(fields=['major'], name='directory_a_major_f12a3d_idx')],
                'unique_together': {('user', 'graduation_year', 'major')},
            },
        ),
    ]
